apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: send-email
  name: send-email
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: send-email
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: send-email
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: "9092"
        - name: KAFKA_URL
          value: kafka-service
        - name: SEND_EMAIL_PORT
          value: "1237"
        image: ajaypremarajan/send-email:latest
        imagePullPolicy: ""
        name: send-email
        ports:
        - containerPort: 1238
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
