apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: test-station
  name: test-station
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: test-station
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: test-station
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: "9092"
        - name: KAFKA_URL
          value: kafka-service
        - name: TEST_STATION_PORT
          value: "1236"
        image: ajaypremarajan/test-station:latest
        imagePullPolicy: ""
        name: test-station
        ports:
        - containerPort: 1236
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
