apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sap-adapter
  name: sap-adapter
spec:
  ports:
  - name: "1234"
    port: 1234
    targetPort: 1234
    nodePort: 31000
  selector:
    io.kompose.service: sap-adapter
  type: NodePort
status:
  loadBalancer: {}
