
server:
  port: ${SAP_ADAPTER_PORT}

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}:${KAFKA_HOST}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: group-id
      bootstrap-servers: ${KAFKA_URL}:${KAFKA_HOST}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      