version: '3.9'
services:
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300

    kibana:
        image: kibana:7.7.0
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch

    logstash:
        image: logstash:7.7.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 127.0.0.1:8089:8089
        volumes:
          - .\logstash:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        restart: unless-stopped
  
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
        - "2181:2181"
        restart: unless-stopped
      
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
        - "9092:9092"
        links:
        - zookeeper
        depends_on:
        - zookeeper
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "test_sap_adapter:1:compact,test_inspect_order:1:compact,test_test_station:1:compact"
        restart: unless-stopped
      
    postgres:
        image: postgres
        container_name: postgres
        ports:
        - "5432:5432"
        environment:
          POSTGRES_DB: inspect_db
          POSTGRES_USER: inspect_db
          POSTGRES_PASSWORD: inspect_db
        restart: unless-stopped
          
    pgadmin:
        image: dpage/pgadmin4
        container_name: pdadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
        ports:
        - "8888:80"
        links:
        - postgres
    
    sap-adapter:
        image: ajaypremarajan/sap-adapter:latest
        container_name: sap-adapter
        links:
        - kafka
        ports:
        - "1234:1234"
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        depends_on:
        - kafka
        - logstash
        
    inspect-order:
        image: ajaypremarajan/inspect-order:latest
        container_name: inspect-order
        links:
        - kafka
        - postgres
        - test-station
        
        ports:
        - "1235:1235"
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inspect_db
          SPRING_DATASOURCE_USERNAME: inspect_db
          SPRING_DATASOURCE_PASSWORD: inspect_db
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        depends_on:
        - kafka
        - postgres
        - logstash
          
    test-station:
        image: ajaypremarajan/test-station:latest
        container_name: test-station
        links:
        - kafka       
        ports:
        - "1236:1236" 
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        depends_on:
        - kafka
        - logstash
        
    inspect-result:
        image: ajaypremarajan/inspect-result:latest
        container_name: inspect-result
        links:
        - kafka
        - postgres
        ports:
        - "1237:1237" 
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inspect_db
          SPRING_DATASOURCE_USERNAME: inspect_db
          SPRING_DATASOURCE_PASSWORD: inspect_db
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        depends_on:
        - kafka
        - postgres
        - logstash
              
    send-email:
        image: ajaypremarajan/send-email:latest
        container_name: send-email
        links:
        - kafka
        - postgres
        ports:
        - "1238:1238"
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        depends_on:
        - kafka
        - logstash
  
 
