apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 80
    nodePort: 32001
  selector:
    io.kompose.service: pgadmin
  type: NodePort
status:
  loadBalancer: {}
