apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: inspect-result
  name: inspect-result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inspect-result
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: inspect-result
    spec:
      containers:
      - env:
        - name: DB_PASS
          value: inspect_db
        - name: DB_URL
          value: jdbc:postgresql://postgres:5432/inspect_db
        - name: DB_USER
          value: inspect_db
        - name: INSPECT_RESULT_PORT
          value: "1237"
        - name: KAFKA_HOST
          value: "9092"
        - name: KAFKA_URL
          value: kafka-service
        image: ajaypremarajan/inspect-result:latest
        imagePullPolicy: ""
        name: inspect-result
        ports:
        - containerPort: 1237
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
